apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnn-backend-pvc
  namespace: lnn-backend
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn